# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1260c54d6db0bd6849cec0a0e48be46c3a272e3bf58be140860a7dd195425a8877457c7bb167d97d582e7f7129eba5ceaae2fbb002e91f5958350473410369f

test:
  secret_key_base: 057ac00ce7639958396224d14eff09d71bd5b41a0d096477bb2362768231943d664241df4114653561ca83f450d9d269e72c2c2add81c39026ca204024d7a973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
